name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: singhragvendra503/pythonrestapi:latest

      - name: Copy manifest files to remote server
        uses: appleboy/scp-action@master
        with:
          host: 3.87.214.85
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: /k8s-menifest/
          target: /home/ubuntu/
      - name: Deploy app on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 3.87.214.85
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
